livreCM =
{
    "livre": [
        {
            "resume": [
                "Dans la nouvelle \"Mario et le magicien\" parue en 1930, Thomas Mann décrit, à travers la personne du narrateur, les expériences d'un père de famille lors de vacances dans la station balnéaire de Torre di Venere, dans le nord de l'Italie, dans les années 20 du siècle dernier.",
                "La famille allemande arrive à la mi-août au Grand Hôtel de Torre, où les clients, principalement italiens, bénéficient d'un traitement de faveur de la part du personnel de l'hôtel. Après quelques jours, la famille se voit contrainte de quitter l'hôtel suite à la plainte injustifiée d'une dame italienne. Même après avoir déménagé dans une pension agréable, le narrateur ne se sent pas bien à Torre. Il y fait extrêmement chaud, la plage est bondée, les Italiens de la classe moyenne y sont bruyants et impitoyables, leurs enfants patriotes. Tout cela est dominé par un état d'esprit nationaliste que le narrateur ressent comme peu amical et xénophobe",
                "Lorsque sa fille de huit ans se montre brièvement nue sur la plage, une vague d'indignation s'empare des baigneurs. Une amende est infligée, mais cet incident n'incite pas la famille à partir plus tôt.",
                "L'arrière-saison commence et des affiches annonçant un spectacle de l'illusionniste Cipolla apparaissent partout. Les enfants du narrateur pressent leurs parents d'acheter des billets, et ceux-ci acceptent avec hésitation.",
                "Des habitants et des invités se rendent à la représentation dans la salle de spectacle, et les enfants découvrent parmi les gens simples des connaissances comme Mario, le serveur, que la famille apprécie.",
                "Le Cavaliere Cipolla apparaît sur scène avec du retard. Son attitude condescendante et ses vêtements élégants mais démodés, tout comme son corps difforme et son autre apparence repoussante, rappellent au narrateur un charlatan des temps passés. Grâce à son aisance verbale, Cipolla s'attire rapidement l'estime des spectateurs, mais pas leur sympathie.",
                "Il n'est pas le magicien et prestidigitateur inoffensif attendu. La démonstration consiste d'abord en des tours d'arithmétique et de cartes. Ce faisant, Cipolla affiche ouvertement son pouvoir sur le public. Il souligne sa supériorité par l'utilisation constante d'une cravache qu'il fait voler dans les airs. Un jeune homme qui ose affronter Cipolla est hypnotisé par celui-ci et forcé de tirer la langue au public.",
                "Pendant l'entracte, le narrateur envisage de quitter le spectacle. Il compare les événements et l'atmosphère de la salle de spectacle avec l'ensemble de son séjour à Torre, se sentant ici comme là-bas à la fois repoussé et étrangement attiré. Il décide de rester.",
                "Après l'entracte, des personnes choisies au hasard dans le public sont hypnotisées par Cipolla. Par la suite, elles font des choses qui vont à l'encontre de leur éducation, de leur pudeur et de leur propre volonté. Ainsi, la tenancière de pension Angiolieri suit Cipolla à travers la salle comme si elle était lunatique, et les appels de son mari effrayé ne lui parviennent pas. Un homme de Rome s'oppose d'abord avec succès à la soumission de Cipolla, mais ce dernier l'emporte et le Romain se met à danser comme Cipolla le lui demande. Son triomphe sur le public atteint ainsi son apogée",
                "Enfin, Cipolla fait signe à Mario, un serveur silencieux et mélancolique, de monter sur scène. Il l'hypnotise jusqu'à ce que celui-ci avoue son amour malheureux pour une jeune fille nommée Silvestra. Cipolla fait croire à l'hypnotisé qu'il est sa maîtresse et demande à Mario de l'embrasser sur la joue. Croyant avoir Silvestra devant lui, il embrasse le sorcier hideux. Mario se réveille de l'hypnose et se précipite hors de la scène, honteux, tandis que le public applaudit avec enthousiasme. Mario se retourne dans sa sortie et tire sur Cipolla.",
                "Le narrateur quitte précipitamment la salle avec ses enfants. Alors que les enfants supposent que les coups de feu font partie du spectacle, le narrateur trouve la fin fatale, mais aussi libératrice.",
                "Pour certains lecteurs, \"Mario et le magicien\" est une observation perspicace des changements en Europe à l'époque de la montée du fascisme. Dans ce contexte, le personnage de Cipolla, qui se croit tout permis, offre de nombreuses possibilités d'interprétation. Thomas Mann lui-même a écrit que la nouvelle était basée sur un fait réel. Partant de là, des questions humaines et morales générales pourraient être mises en avant dans ce classique. Quoi qu'il en soit, cette matière dense constitue une bonne introduction à la langue et au style de Thomas Mann"
            ]
        }
    ]
}
