livreCM =
{
    "livre": [
        {
            "resume": [
                "Dans la nouvelle \"Mario et le magicien\" parue en 1930, Thomas Mann décrit, à travers la personne du narrateur, les expériences d'un père de famille lors de vacances dans la station balnéaire de Torre di Venere, dans le nord de l'Italie, dans les années 20 du siècle dernier.",
                "La famille allemande arrive à la mi-août au Grand Hôtel de Torre, où les clients, principalement italiens, bénéficient d'un traitement de faveur de la part du personnel de l'hôtel. Après quelques jours, la famille se voit contrainte de quitter l'hôtel suite à la plainte injustifiée d'une dame italienne. Même après avoir déménagé dans une pension agréable, le narrateur ne se sent pas bien à Torre. Il y fait extrêmement chaud, la plage est bondée, les Italiens de la classe moyenne y sont bruyants et impitoyables, leurs enfants patriotes. Tout cela est dominé par un état d'esprit nationaliste que le narrateur ressent comme peu amical et xénophobe",
                "Lorsque sa fille de huit ans se montre brièvement nue sur la plage, une vague d'indignation s'empare des baigneurs. Une amende est infligée, mais cet incident n'incite pas la famille à partir plus tôt.",
                "L'arrière-saison commence et des affiches annonçant un spectacle de l'illusionniste Cipolla apparaissent partout. Les enfants du narrateur pressent leurs parents d'acheter des billets, et ceux-ci acceptent avec hésitation.",
                "Des habitants et des invités se rendent à la représentation dans la salle de spectacle, et les enfants découvrent parmi les gens simples des connaissances comme Mario, le serveur, que la famille apprécie.",
                "Le Cavaliere Cipolla apparaît sur scène avec du retard. Son attitude condescendante et ses vêtements élégants mais démodés, tout comme son corps difforme et son autre apparence repoussante, rappellent au narrateur un charlatan des temps passés. Grâce à son aisance verbale, Cipolla s'attire rapidement l'estime des spectateurs, mais pas leur sympathie.",
                "Il n'est pas le magicien et prestidigitateur inoffensif attendu. La démonstration consiste d'abord en des tours d'arithmétique et de cartes. Ce faisant, Cipolla affiche ouvertement son pouvoir sur le public. Il souligne sa supériorité par l'utilisation constante d'une cravache qu'il fait voler dans les airs. Un jeune homme qui ose affronter Cipolla est hypnotisé par celui-ci et forcé de tirer la langue au public.",
                "Pendant l'entracte, le narrateur envisage de quitter le spectacle. Il compare les événements et l'atmosphère de la salle de spectacle avec l'ensemble de son séjour à Torre, se sentant ici comme là-bas à la fois repoussé et étrangement attiré. Il décide de rester.",
                "Après l'entracte, des personnes choisies au hasard dans le public sont hypnotisées par Cipolla. Par la suite, elles font des choses qui vont à l'encontre de leur éducation, de leur pudeur et de leur propre volonté. Ainsi, la tenancière de pension Angiolieri suit Cipolla à travers la salle comme si elle était lunatique, et les appels de son mari effrayé ne lui parviennent pas. Un homme de Rome s'oppose d'abord avec succès à la soumission de Cipolla, mais ce dernier l'emporte et le Romain se met à danser comme Cipolla le lui demande. Son triomphe sur le public atteint ainsi son apogée",
                "Enfin, Cipolla fait signe à Mario, un serveur silencieux et mélancolique, de monter sur scène. Il l'hypnotise jusqu'à ce que celui-ci avoue son amour malheureux pour une jeune fille nommée Silvestra. Cipolla fait croire à l'hypnotisé qu'il est sa maîtresse et demande à Mario de l'embrasser sur la joue. Croyant avoir Silvestra devant lui, il embrasse le sorcier hideux. Mario se réveille de l'hypnose et se précipite hors de la scène, honteux, tandis que le public applaudit avec enthousiasme. Mario se retourne dans sa sortie et tire sur Cipolla.",
                "Le narrateur quitte précipitamment la salle avec ses enfants. Alors que les enfants supposent que les coups de feu font partie du spectacle, le narrateur trouve la fin fatale, mais aussi libératrice.",
                "Pour certains lecteurs, \"Mario et le magicien\" est une observation perspicace des changements en Europe à l'époque de la montée du fascisme. Dans ce contexte, le personnage de Cipolla, qui se croit tout permis, offre de nombreuses possibilités d'interprétation. Thomas Mann lui-même a écrit que la nouvelle était basée sur un fait réel. Partant de là, des questions humaines et morales générales pourraient être mises en avant dans ce classique. Quoi qu'il en soit, cette matière dense constitue une bonne introduction à la langue et au style de Thomas Mann"
            ],
            "auteur": "Thomas Mann (1875-1955) est un écrivain allemand, lauréat du prix Nobel de littérature en 1929. C'est un romancier, essayiste, nouvelliste, critique social, diariste, scénariste, professeur d'université, écrivain. Il est l'une des figures les plus éminentes de la littérature européenne de la première moitié du xxe siècle et est considéré comme un grand écrivain moderne de la décadence. Rompant peu à peu avec les formes littéraires traditionnelles, ses ouvrages comprenant romans, nouvelles et essais, font appel aux domaines des sciences humaines (histoire, philosophie, politique, analyse littéraire) pour produire une image du siècle et de ses bouleversements. Son œuvre, influencée par Arthur Schopenhauer, est centrée sur l'étude des rapports entre l'individu et la société. Elle oppose généralement la rigueur du travail intellectuel, la spiritualité et le culte de l'action. Cependant, Mann refuse de lier son existence à la décadence. Il n'aura de cesse de lutter à sa manière, comme son frère Heinrich, pour la défense des valeurs mises en péril par les différents « ismes » et les idéologies radicales. Au fil du temps, il devient une figure réellement engagée dans l'action politique et éthique. L'homme, au départ porteur de lourds préjugés venus de son pays et de son époque, fait face dans les moments difficiles et s'érige en représentant de la « bonne Allemagne » et de ses meilleures traditions.",
            "analyse": "La nouvelle \"Mario et l'enchanteur\" est à la fois une réflexion sensible sur l'ambiance en Italie à l'époque du fascisme et une analogie imagée sur le danger de la séduction du peuple par des leaders charismatiques. La première section de cette interprétation détaillée de la nouvelle est consacrée à la manière dont le fascisme est abordé dans la nouvelle. La deuxième section décrit de manière compréhensible le thème philosophiquement difficile à saisir du libre arbitre et interprète le rôle de cette abstraction socialement importante dans la nouvelle. L'esprit du nationalisme, est décrit d'une manière très particulière dans la nouvelle, à travers les yeux du touriste allemand en Italie.",
            "style": "",
            "personnage":"",
            "lien": "",
            "intro": [
                "Le souvenir de Torre di Venere est désagréable du point de vue de l'atmosphère. Dès le début, il y avait de la colère, de l'irritation, de la tension dans l'air, et à la fin, il y avait le choc avec ce terrible Cipolla, en la personne duquel le mal particulier de l'ambiance semblait s'incarner de manière fatale et d'ailleurs humainement très impressionnante, et s'accumuler de manière menaçante. Le fait que les enfants aient dû être présents lors de la fin avec horreur (une fin qui nous a semblé après coup toute tracée et inhérente à l'essence des choses) était une triste incongruité en soi, due à un malentendu et aux faux semblants de cet homme étrange. Heureusement, ils n'ont pas compris où s'arrêtait le spectacle et où commençait la catastrophe, et on les a laissés dans l'heureuse illusion que tout cela n'était que du théâtre. Torre se trouve à une quinzaine de kilomètres de Portoclemente,  l'une des stations estivales les plus populaires de la mer Tyrrhénienne, élégante et urbaine, bondée pendant des mois, avec une rue d'hôtels et de bazars colorés le long de la mer, une large plage recouverte de capanes, de châteaux aux fanions et d'humanité brune, et une animation bruyante. Comme la plage, accompagnée de pins sur lesquels se détachent les montagnes, conserve tout au long de la côte son espace de sable fin et confortable, il n'est pas étonnant qu'une concurrence plus calme se soit déjà manifestée : Torre di Venere, où l'on cherche d'ailleurs en vain depuis longtemps la tour à laquelle elle doit son nom, est une station touristique dérivée de la grande station balnéaire voisine et a été pendant quelques années une idylle pour quelques-uns, un refuge pour les amis de l'élément immatériel. Mais comme il arrive avec de tels lieux, la paix a dû s'éloigner depuis longtemps, le long de la côte, vers Marina Petriera et Dieu sait où ; le monde, on le sait, le cherche et le chasse en se jetant sur lui avec une nostalgie ridicule, en s'imaginant qu'il peut se marier avec lui, et que là où il est, il peut être ; oui, quand il a déjà installé sa foire à la place, il est capable de croire qu'il est encore là. C'est ainsi que Torre, bien que toujours plus tranquille et plus modeste que Portoclemente,  a été fortement accueillie par les Italiens et les étrangers. On ne va plus au bain universel, même si ce n'est que dans la mesure où celui-ci reste un bain universel bruyant et complet ; on va à côté, à Torre, c'est même plus raffiné, c'est en ",
                "outre moins cher, et la force d'attraction de ces caractéristiques continue à faire ses preuves, alors que les caractéristiques elles-mêmes n'existent déjà plus.Torre s'est dotée d'un Grand Hôtel ; de nombreuses pensions, plus ou moins sophistiquées, ont vu le jour ; les propriétaires et les locataires des maisons d'été et des jardins de pinède surplombant la mer ne sont plus du tout tranquilles sur la plage ; en juillet et en août, rien ne distingue plus cet endroit de celui de Portoclemente : il y a une foule de baigneurs qui s'agitent, se chamaillent, s'excitent, dont le soleil brûlant écorche la peau de la nuque, des barques à fond plat, peintes de couleurs criardes, occupées par des enfants dont les prénoms sonores sont lancés par des mères qui font le guet, remplissent les airs d'une inquiétude rauque, se balancent sur l'azur étincelant et, marchant sur les membres des campeurs, les vendeurs d'huîtres, de boissons, de fleurs, de bijoux en corail et de cornetti al burro, eux aussi avec la voix forte et ouverte du Sud, proposent leur marchandise. C'est ainsi que se présentait la plage de Torre à notre arrivée - assez jolie, mais nous trouvions tout de même que nous étions arrivés trop tôt. C'était la mi-août, la saison italienne battait encore son plein ; ce n'est pas le bon moment pour les étrangers d'apprécier les charmes de l'endroit. Quelle cohue l'après-midi dans les cafés-jardins du bord de mer, par exemple à l'\"Esquisito\", où nous étions parfois assis et où Mario nous servait, ce même Mario dont je vais vous parler tout de suite ! On trouve difficilement une table, et les orchestres, sans que l'un veuille connaître l'autre, s'interpellent confusément. L'après-midi, il y a d'ailleurs une affluence quotidienne de Portoclemente ; car Torre est bien sûr un but d'excursion apprécié par la clientèle agitée de ce lieu de plaisir, et grâce aux voitures Fiat qui vont et viennent, les buissons de lauriers et de lauriers-roses au bord de la route de campagne qui les relie sont recouverts d'une épaisse couche de poussière blanche - un spectacle étrange, mais repoussant. Plus sérieusement, il faut se rendre à Torre di Venere en septembre, lorsque les bains se sont vidés de leur public, ou en mai, avant que la chaleur de la mer n'ait atteint le degré qui gagne les méridionaux à y plonger. L'avant et l'arrière-saison ne sont pas non plus vides, mais l'ambiance y est plus feutrée et moins nationale. L'anglais, l'allemand ",
                "et le français dominent sous les toiles d'ombrage des capanes et dans les salles à manger des pensions, tandis que l'étranger trouve encore en août au moins le Grand Hôtel, où nous avons occupé des chambres faute d'adresses personnelles, tellement entre les mains de la société florentine et romaine qu'il peut se sentir isolé et momentanément comme un hôte de second rang."
            ],
            "livre": [
                [
                    "Nous en avons fait l'expérience avec un peu de dépit le soir de notre arrivée, lorsque nous nous sommes retrouvés à dîner dans la salle à manger et que le serveur nous a désigné une table. Il n'y avait rien à redire à cette table, mais nous étions captivés par l'image de la véranda attenante, qui donnait sur la mer, aussi forte que la salle, mais pas totalement occupée, et sur les petites tables de laquelle brillaient des lampes à écran rouge. Les petits se montrèrent enchantés de cette fête, et nous manifestâmes simplement notre décision de prendre nos repas dans la véranda - une manifestation d'ignorance, comme on le vit, car on nous signifia avec une politesse un peu gênée que ce séjour accueillant était réservé à \"notre clientèle\", \"ai nostri clienti\".",
                    "Nos clients ? Mais c'était nous. Nous n'étions pas des passants ou des éphémères, mais des résidents, des pensionnaires, pour trois ou quatre semaines. Nous n'avons d'ailleurs pas insisté sur la différence entre nos semblables et cette clientèle qui avait le droit de manger à la lumière rougeoyante, et nous avons pris le pranzo à notre table de salle, éclairée de manière générale et objective - un repas assez médiocre, un schéma d'hôtel sans caractère et sans saveur ; nous avons ensuite trouvé la cuisine bien meilleure à la Pensione Eleonora, à dix pas dans les terres.",
                    "C'est là que nous nous sommes installés avant même de nous être réchauffés au Grand Hôtel, au bout de trois ou quatre jours, - non pas à cause de la véranda et de ses petites lampes : les enfants, immédiatement amis avec les serveurs et les grooms, pris d'une envie de mer, avaient très vite chassé de leur esprit cette attirance colorée. Mais avec certains clients de la véranda, ou plus exactement avec la direction de l'hôtel qui les servait avec amour, il y eut aussitôt un de ces conflits qui peuvent marquer un séjour du sceau de l'inconfort dès le début.",
                    "Il y avait parmi eux de la haute noblesse romaine, un prince X. et sa famille, et comme les chambres de ces messieurs étaient voisines des nôtres, la princesse, à la fois grande dame et mère passionnée, avait été effrayée par les traces résiduelles d'une coqueluche que nos petits avaient surmontée ensemble peu de temps auparavant, et dont les faibles rémanences interrompaient parfois encore la nuit le sommeil habituellement inébranlable du plus jeune. La nature de cette maladie est peu expliquée, la superstition a ici toute sa place, et nous n'avons jamais reproché à notre élégante voisine d'adhérer à l'opinion largement répandue selon laquelle la coqueluche est acoustiquement contagieuse, et de craindre simplement le mauvais exemple pour ses petits. Dans la plénitude féminine de son prestige, elle a fait des démarches auprès de la direction, et celle-ci, en la personne du célèbre manager en redingote, s'est empressée de nous signifier, avec beaucoup de regrets, que dans ces conditions, notre relogement dans le bâtiment annexe de l'hôtel était une nécessité incontournable. Nous avons bien fait d'affirmer que la maladie infantile était au stade de la dernière régression, qu'elle devait être considérée comme surmontée et qu'elle ne représentait plus aucun danger pour l'entourage. Tout ce que l'on nous a accordé, c'est que le cas soit porté devant le forum médical et que le médecin de la maison - lui seul, pas un médecin que nous aurions désigné - soit appelé à trancher. Nous avons accepté cet accord, convaincus que cela permettrait à la fois de rassurer la princesse et d'éviter pour nous l'inconvénient d'un déménagement. Le docteur arrive et se révèle être un serviteur loyal et droit de la science. Il examine le petit, déclare que le mal est passé et nie toute inquiétude.",
                    "Nous nous croyons déjà en droit de penser que l'incident est réglé : le manager déclare alors que nous quittons les chambres et que nous nous installons dans la dépendance, même après les constatations du médecin. Ce byzantinisme nous a indignés. Il est peu probable que l'obstination à ne pas tenir parole à laquelle nous nous sommes heurtés ait été celle de la princesse. L'aubergiste serviable n'avait sans doute même pas osé lui faire part du vote du docteur. Quoi qu'il en soit, nous l'avons informé que nous préférions quitter l'hôtel immédiatement et nous avons fait nos bagages. Nous pouvions le faire le cœur léger, car entre-temps nous avions déjà noué des liens avec la Pensione Eleonora, dont l'aspect privé et sympathique nous avait tout de suite frappés, et nous avions fait une connaissance très sympathique en la personne de sa propriétaire, la Signora Angiolieri. Madame Angiolieri, une petite dame aux yeux noirs, de type toscan, probablement au début de la trentaine, avec le teint d'ivoire mat des méridionales, et son époux, un homme soigneusement vêtu, silencieux et chauve, possédaient à Florence une grande maison d'hôtes et ne présidaient la succursale de Torre di Venere qu'en été et au début de l'automne. Mais auparavant, avant son mariage, notre nouvelle hôtesse avait été la dame de compagnie, la compagne de voyage, l'habilleuse et même l'amie de Duse, une époque qu'elle considérait apparemment comme la grande, l'heureuse de sa vie, et dont elle commença à parler avec vivacité lors de notre première visite. De nombreuses photographies de la grande actrice, accompagnées de dédicaces chaleureuses, ainsi que d'autres souvenirs de la vie commune d'autrefois, ornaient les petites tables et les étagères du salon de Mme Angiolieri, et bien qu'il soit évident que le culte de son intéressant passé voulait aussi un peu augmenter le pouvoir d'attraction de son entreprise actuelle, nous avons écouté avec plaisir et intérêt, tout en étant guidés à travers la maison, les récits qu'elle nous a faits en toscan, en staccato et en tintinnabulant, de la bonté souffrante, du génie du cœur et de la profonde délicatesse de sa maîtresse immortalisée.",
                    "C'est donc là que nous avons fait porter nos affaires, au grand dam du personnel du Grand Hôtel, qui, en bon Italien, aimait beaucoup les enfants ; L'appartement qui nous a été attribué était fermé et agréable, le contact avec la mer était confortable, grâce à une allée de jeunes platanes qui rejoignait la promenade, la salle à manger, où Madame Angiolieri remplissait chaque midi la soupe de ses propres mains, était fraîche et propre, le service attentif et agréable, la nourriture excellente, il y avait même des connaissances viennoises avec lesquelles on bavardait devant la maison après le dîner et qui nous ont permis de faire d'autres connaissances, et ainsi tout aurait pu être bon - nous étions parfaitement contents de notre échange, et rien ne manquait en fait pour un séjour satisfaisant. Pourtant, nous n'étions pas vraiment à l'aise. Peut-être l'occasion insensée de notre changement de quartier nous hantait-elle malgré tout, - j'avoue personnellement que j'ai du mal à me remettre de tels heurts avec l'humain ordinaire, l'abus naïf du pouvoir, l'injustice, la corruption rampante. Ils m'ont occupé trop longtemps, m'ont plongé dans une réflexion irritée, qui doit sa stérilité à l'évidence et au naturel démesurés de ces phénomènes. Pourtant, nous ne nous sentions même pas en désaccord avec le Grand Hôtel. Les enfants continuaient à y entretenir leurs amitiés, le valet de pied réparait leurs jouets, et de temps en temps nous prenions le thé dans le jardin de l'établissement, non sans avoir aperçu la princesse qui, les lèvres retroussées comme du corail, apparaissait à pas gracieux et fermes pour aller voir ses chéris encadrés par une Anglaise, sans se douter de notre proximité inquiétante, car il était strictement interdit à notre petit, dès qu'elle se montrait, de se racler la gorge.",
                    "La chaleur était excessive, dois-je l'évoquer ? Elle était africaine : le règne terrible du soleil dès qu'on se détachait de l'ourlet de fraîcheur indigo, d'une implacabilité qui faisait des quelques pas entre la plage et la table de midi, même en pyjama nu, une entreprise hantée d'avance. Vous aimez ça ? Vous aimez ça pendant des semaines ? Certes, c'est le Sud, c'est le temps classique, le climat de la culture humaine en plein essor, le soleil d'Homère et ainsi de suite. Mais au bout d'un moment, je ne peux pas m'empêcher de le trouver ennuyeux. Le vide ardent du ciel, jour après jour, me pèse bientôt, l'éclat des couleurs, l'immense naïveté et la continuité de la lumière suscitent certes des sentiments festifs, ils garantissent l'insouciance et une indépendance certaine vis-à-vis des caprices et des contretemps météorologiques ; mais sans qu'on en rende compte au début, ils laissent insatisfaits de façon désastreuse les besoins plus profonds et moins simples de l'âme nordique et inspirent à la longue quelque chose comme du mépris. Vous avez raison, sans cette stupide histoire de coqueluche, je ne l'aurais sans doute pas ressenti de cette manière ; j'étais irrité, je voulais peut-être le ressentir et j'ai repris, à moitié inconsciemment, un motif mental prêt à l'emploi pour, sinon créer, du moins légitimer et renforcer ce ressenti. Mais comptez ici sur notre mauvaise volonté, - en ce qui concerne la mer, la matinée passée sur le sable fin, devant sa gloire éternelle, il ne peut être question de cela, et pourtant, contre toute expérience, nous ne nous sentions pas bien, pas heureux, même sur la plage."
                ]
            ]
        },
        {
            "resume": [
                "Dans le récit Le ciel partagé de Christa Wolf, Rita raconte son histoire avec Manfred en rétrospective. Elle est hospitalisée et raconte comment elle a rencontré Manfred et comment elle a quitté son village natal pour venir en ville. Rita fait la connaissance de Manfred dans son village natal, lors d'un bal. Manfred est un jeune homme d'une vingtaine d'années, très sérieux, qui réfléchit et parle de manière froide et rationnelle de son travail de chimiste. Rita arrive en ville avec Manfred et s'installe avec lui chez ses parents, avec lesquels Manfred n'a pas non plus de bonnes relations. Rita vient de grandir et est encore très maladroite et naïve. Elle ne semble pas encore très à l'aise seule dans la grande ville. Lorsqu'elle commence à travailler dans une grande entreprise où elle accompagne une formation, car elle suit parallèlement une formation d'enseignante et doit collaborer au système socialiste et effectuer un travail physique difficile. Au début, elle a du mal à s'orienter dans cette grande usine. Ses collègues de travail ont des sentiments très mitigés à son égard, car c'est une jeune femme qui ne semble pas encore avoir une idée précise de la vie. Elle a toujours eu une relation de confiance avec Manfred. Manfred n'aime pas ses parents et en parle régulièrement avec Rita. Elle aime Manfred, bien qu'il soit si différent d'elle, avec son caractère naïf, elle semble même l'adorer au début, mais cette relation change, car plus elle vit dans la grande ville et plus elle a affaire à ses collègues de travail, qu'elle gagne même bientôt comme amis ou comme bonnes connaissances, plus elle semble sortir d'elle-même et perd son côté juvénile. Ce changement a également pour conséquence de modifier la relation entre Rita et Manfred. À la fin, Manfred est tellement perturbé par le système socialiste de la RDA qu'il préfère partir à l'Ouest. Rita voyage à sa suite, mais ne peut rien faire avec le système de la RFA et retourne, résignée, chez son beau-père en devenir, qui la renvoie à son collègue de travail, qui aimerait bien la voir, mais qui est gravement malade. Elle raconte son histoire rétrospectivement depuis l'hôpital, après s'être évanouie lors d'une tentative de suicide."
            ],
            "auteur": "Christa Wolf, née le 18 mars 1929 à Landsberg an der Warthe et décédée le 1 décembre 2011 à Berlin est une écrivaine allemande. Elle comptait parmi les personnalités littéraires les plus importantes de la RDA et a été récompensée à de nombreuses reprises, notamment par le prix Georg Büchner. Son œuvre a été traduite dans de nombreuses langues.",
            "style": "L'ensemble du récit se déroule sur deux niveaux. Le premier niveau se déroule à l'hôpital (après son accident) et est raconté par Rita dans le discours d'un narrateur omniscient (auctorial). Elle y décrit au présent comment se déroule sa vie à l'hôpital (conversations avec les visiteurs, etc.) Ce niveau est donc le présent. Le deuxième niveau décrit toute l'action, tout ce qui est écrit dans le résumé du contenu. Ce niveau est décrit au prétérit, mais aussi au discours direct par une troisième personne. Cette personne n'est pas une personne du récit, c'est simplement le narrateur, qui a également plus d'informations que Rita elle-même. ",
            "personnage": "Avec le temps, elle gagne en maturité et prend de plus en plus de décisions par elle-même, par exemple en déménageant en ville. Elle est également une personne très importante pour Manfred. Ainsi, elle l'écoute souvent patiemment pendant que celui-ci lui raconte ses soucis. Et elle lui donne souvent de bons conseils. De ce point de vue, elle joue aussi le rôle des parents, pour lesquels Manfred n'a pas de sentiments très profonds et à qui il ne demanderait donc jamais d'aide. Mais l'inverse est également vrai. Manfred doit aussi souvent apparaître comme un consolateur pour Rita. En conclusion, on peut dire que Rita est devenue une femme indépendante et mûre, capable de maîtriser sa vie et de se relever après plusieurs coups du sort (mort de son père, séparation d'avec Manfred, ...) et de continuer à avancer.",
            "lien": "Christa Wolf évite les contenus typiques de la littérature de propagande socialiste en abordant simplement et directement la situation de l'économie et les raisons du manque d'approvisionnement matériel de la population - c'est tout ce que fait l'auteur. Au final, c'est toujours l'idée positive et confiante qui prévaut, et les exigences du régime socialiste en matière de littérature sont ainsi malgré tout remplies. Wolf dresse un tableau réaliste de l'évolution de la RDA, partant d'une société précommuniste pour aboutir à la lente marche vers le socialisme du début des années soixante. Rita et Manfred représentent les deux formes de société rivales de l'époque. Pour Manfred, la seule possibilité de lutter contre l'arbitraire et l'incompétence des dirigeants politiques de la RDA est de fuir en RFA. Rita, en revanche, reconnaît certes les défauts du système socialiste, mais elle est prête à accepter des pertes matérielles pour apporter sa part au processus de perfectionnement de l'idée socialiste.",
            "analyse": "",
            "intro": [
                
            ],
            "livre": [
                [

                ]
            ]
        }
    ]
}
